--SELECCIÓN DE BD
USE dsrp_registro_salud
--CREACIÓN DE TABLAS

create table PACIENTE (ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL, DNI VARCHAR(20) UNIQUE NOT NULL,nombre varchar(225) NOT null,
	apellido varchar(100) NOT null,
	direccion varchar(100) null,
	telefono varchar(20) NULL,
	correo varchar(100) NULL,
	estado_civil varchar(100) NULL
	);
--TIPO DE VISITA
create table TIPO_VISITA (ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
NOMBRE VARCHAR(100)  NOT NULL, PACIENTE varchar(225))

-- DETALLE DE LA VISITA
create table DETALLE_VISITA (ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
ID_PACIENTE INT NOT NULL,VISITA_ID INT NOT NULL
CONSTRAINT KF_DATALLE_VISITA FOREIGN KEY ( ID_PACIENTE) REFERENCES PACIENTE(ID),
CONSTRAINT KF_VISITA_ID FOREIGN KEY ( VISITA_ID) REFERENCES VISITA(ID));

--TABLA VISITA
create table VISITA (ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
FECHA DATETIME DEFAULT GETDATE() NOT NULL , TIPO_VISITA_ID INT,CENTRO_SALUD varchar(225) NOT null,
	ID_PACIENTE INT,
	SIGNOS_VITALES varchar(1000) null,
	OBSERVACIONES varchar(225) NULL
	CONSTRAINT FK_TIPO_VISITA_ID FOREIGN KEY (TIPO_VISITA_ID) REFERENCES TIPO_VISITA(ID));

--TABLA TIPOS REGISTROS

create table TIPO_REGISTRO (ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
NOMBRE VARCHAR (20) NOT NULL,DETALLE VARCHAR (100) NOT NULL
);

--TABLA CENTROS DE SALUD

create table CENTRO_SALUD (ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
NOMBRE VARCHAR (20) NOT NULL,DIRECCIÓN VARCHAR (100) NOT NULL, TELEFONO VARCHAR(100)NULL);

--TABLA REGISTRO DE SALUD

create table REGISTRO_SALUD (ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
TIPO_REGISTRO_ID INT NOT NULL , 
VISITA INT NOT NULL ,
 ID_PACIENTE INT NOT null,
	SUCURSALES_ID INT NOT NULL,
	RESULTADO VARCHAR (100) NULL,
	PRESIÓN_ARTERIAL VARCHAR NOT NULL,
	FRECUENCIA VARCHAR (100) NOT NULL,
	PESO VARCHAR (100) NOT NULL,
	TRATAMIENTO VARCHAR (250) NULL,
	CREATED_AT DATETIME DEFAULT GETDATE() NOT NULL, 
	UPDATED_AT DATETIME NULL,
	DELETED_AT DATETIME NULL,
	CREATED_BY INT NOT NULL, 
	UPDATED_BY INT NULL,
	CONSTRAINT FK_TIPO_REGEISTRO_ID FOREIGN KEY (TIPO_REGISTRO_ID) REFERENCES TIPO_REGISTRO(ID),
	CONSTRAINT FK_VISITA FOREIGN KEY (VISITA) REFERENCES VISITA(ID),
	CONSTRAINT FK_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES VISITA (ID),
	CONSTRAINT FK_SUCURSALES_ID FOREIGN KEY (SUCURSALES_ID) REFERENCES CENTRO_SALUD (ID));